update deployment and cluster role
Granulate/gmaestro-helm pull request #2
Opened 2023-08-31 09:30 UTC by marina-vrublevsky

2023-08-31 12:00 UTC, alonbentamar requested changes

2023-08-31 12:00 UTC, alonbentamar commented on chart/templates/granulate-maestro-deployment.yaml
> +      - name: granulate-secret
We shouldn't need this

2023-08-31 12:00 UTC, alonbentamar commented on gmaestro-1.0.0-latest.tgz
What is this file?

2023-08-31 12:48 UTC, marina-vrublevsky commented on gmaestro-1.0.0-latest.tgz
this is the versioned chart archive file, not sure it's necessary here but it was already here so i updated it just in case

2023-08-31 13:30 UTC, alonbentamar submitted a review, later dismissed

2023-09-03 11:29 UTC, marina-vrublevsky commented
@alonbentamar according to [helm's docs ](https://helm.sh/docs/topics/chart_repository/#managing-chart-repositories) the index and the packaged chart should be inside the chart directory

2023-09-03 12:27 UTC, alonbentamar approved these changes

2023-09-03 13:08 UTC, merged